name: Bug report
description: Report something broken
labels: ["bug"]
body:
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: What did you expect vs what happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Run ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Logs / screenshots
      render: shell
  - type: input
    id: env
    attributes:
      label: Environment
      placeholder: "Codespaces / Pi 5 / OS version / Python version"