name: Decision
description: Capture an architecture/product decision
labels: ["decision"]
body:
  - type: textarea
    id: context
    attributes:
      label: Context
    validations:
      required: true
  - type: textarea
    id: options
    attributes:
      label: Options considered
      placeholder: |
        - Option A:
        - Option B:
    validations:
      required: true
  - type: textarea
    id: decision
    attributes:
      label: Decision
    validations:
      required: true